# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- set_fact:
    assign_public_ip: "{{ 'web' in tags }}"

- include: "{{provider}}.yml"

- name: Refresh dynamic inventory
  run_once: yes
  command: tm_inventory --refresh-cache
  environment:
    TM_SETUP: "{{ tm_setup_file }}"

- meta: refresh_inventory
  run_once: yes

- pause:
    minutes: 1
    prompt: "Wait 1 minute for instance."

- include: python.yml
  delegate_to: "{{ instance_name }}"
  delegate_facts: yes
  when: instance_state == "present"

- include: format.yml
  delegate_to: "{{ instance_name }}"
  delegate_facts: yes
  when:
    - volume_size is defined
    - instance_state == "present"

- include: mount.yml
  delegate_to: "{{ instance_name }}"
  delegate_facts: yes
  when:
    - volume_size is defined
    - instance_state == "present"

- include: create_user.yml
  delegate_to: "{{ instance_name }}"
  delegate_facts: yes
  when: instance_state == "present"
