# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019 University of Zurich.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

- name: Install NFS support (Debian/Ubuntu)
  apt:
    name:
      - nfs-common
  when: 'ansible_os_family == "Debian"'

- name: Install NFS support (CentOS/RHEL)
  apt:
    name:
      - nfs-utils
  when: 'ansible_os_family == "RedHat"'

- name: Mount TM root from front-end server
  mount:
    path: '{{ tm_root }}'
    src: 'groups.tissuemaps_server[0]:{{ tm_root }}'
    fstype: nfs
    opts: rw,async
    state: present
