# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# We need to update the apt repository based on the latest Postgres version
# such that the correct version of postgresql-client package will be installed.
- name: Add PostgreSQL apt repository (url)
  lineinfile:
    dest: /etc/apt/sources.list.d/pgdg.list
    state: present
    create: yes
    regexp: '^deb http\\:\\/\\/apt.postgresql'
    line: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
  register: pgs_aptrepo
  tags:
    - database

- name: Add PostgreSQL apt repository (key)
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
    validate_certs: no
  register: pgs_aptkey
  tags:
    - database

- name: Update apt packages to add PostgreSQL
  tags:
    - update
    - database
  shell: aptitude update
  when: pgs_aptkey.changed or pgs_aptrepo.changed

- name: Install apt packages for PostgreSQL client
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql-client-{{ postgresql_version }}
    - libpq-dev
  tags:
    - database

