# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: Install yum packages required for Python
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-devel
    - python-pip
    - tkinter
    - tk-devel
    - python-setuptools
    - libffi-devel
    - readline-devel
  when: ansible_os_family == 'RedHat'
  tags:
    - python

- name: Install yum packages required by Python packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - openblas-devel
    # gc3pie:
    - time
    # h5py:
    - hdf5-devel
    # lxml:
    - libxml2-devel
    - libxslt-devel
    # # matplotlib:
    # - pyqt4-dev-tools
    # - libfreetype6-dev
    # - python-tk
    # shapely:
    - geos-devel
  when: ansible_os_family == 'RedHat'
  tags:
    - python

