# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: Install bower and gulp node packages
  npm:
    name: "{{ item }}"
    state: present
    path: "{{ tmui_dir }}/src"
  loop:
    - bower
    - gulp
  tags:
    - web-server
    - tissuemaps

- name: Install dependencies from `package.json`
  npm:
    path: "{{ tmui_dir }}/src/"
    state: present
  tags:
    - web-server
    - tissuemaps

- name: Install dependencies from `bower.json`
  bower:
    path: "{{ tmui_dir }}/src"
    state: present
  tags:
    - web-server
    - tissuemaps

- name: Update gulp proxy settings
  replace:
    dest: "{{ tmui_dir }}/src/tasks/server.js"
    regexp: '{{ item.search }}'
    replace: '{{ item.replace }}'
  with_items:
    - search: 'target:\s.http.*$'
      replace: "target: 'http://{{ app_host }}:{{ app_port }}',"
    - search: 'changeOrigin:\s.*$'
      replace: "xfwd: true"
  when: app_host != 'unix'
  tags:
    - web-server
    - tissuemaps

- name: Build client code for production deployment
  command: gulp build --prod
  args:
    chdir: "{{ tmui_dir }}/src"
  tags:
    - web-server
    - tissuemaps

- name: Allow web server to read TmUI JS files
  tags:
    - web-server
    - tissuemaps
  file:
    path: "{{ tm_www_root }}"
    state: directory
    recurse: yes
    mode: 'a+rX'
