# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
- name: Add user groups
  become: yes
  group:
    name: "{{ item }}"
  with_items:
    - "{{ tm_group }}"
    - "{{ db_group }}"

- name: Add `tissuemaps` user
  become: yes
  user:
    name: "{{ tm_user }}"
    group: "{{ tm_group }}"
    shell: /bin/bash
    system: yes
    home: '/home/tissuemaps'
    createhome: yes
    append: yes

- name: Add `postgres` user
  become: yes
  user:
    name: "{{ db_user }}"
    group: "{{ db_group }}"
    shell: /bin/sh
    system: yes
    home: '/var/lib/postgresql'
    createhome: yes
    append: yes

- name: Allow tm_user to use SLURM's `sacctmgr`
  become: yes
  lineinfile:
    dest: '/etc/sudoers.d/{{ tm_user }}'
    line: "{{ tm_user }} ALL=(root) NOPASSWD:/usr/bin/sacctmgr"
    state: present
    create: yes

- name: Allow tm_user to control TM services (I)
  become: yes
  lineinfile:
    dest: '/etc/sudoers.d/{{ tm_user }}'
    line: "{{ tm_user }} ALL=(root) NOPASSWD:/usr/bin/supervisorctl {{ item[0] }} {{ item[1] }}"
    state: present
    create: yes
  with_nested:
    # actions
    - ['start', 'restart', 'stop', 'update']
    # services
    - ['tm_server', 'tm_jobdaemon']

- name: Allow tm_user to control TM services (II)
  become: yes
  lineinfile:
    dest: '/etc/sudoers.d/{{ tm_user }}'
    line: "{{ tm_user }} ALL=(root) NOPASSWD:/usr/bin/supervisorctl reread"
    state: present
    create: yes

- name: Create SSH directory for tm_user
  become: yes
  file:
    path: "{{ tm_home }}/.ssh"
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0700

- name: Enable SSH access for tm_user
  become: yes
  copy:
    src: /home/{{ ansible_user }}/.ssh/authorized_keys
    remote_src: yes
    dest: "{{ tm_home }}/.ssh/authorized_keys"
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0700
