# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016  Markus D. Herrmann, University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# We need to remove an existing database cluster, otherwise initdb will fail.
- name: Check if default data directory exists
  stat:
    path: "{{ db_default_cluster_data_directory }}"
  register: stat_default_db_data_directory
  tags:
    - database

- name: Check if default database is running
  stat:
    path: "{{ db_default_cluster_data_directory }}/postmaster.pid"
  register: stat_default_db_pid
  tags:
    - database

- name: Stop running default database server
  command: /usr/local/sbin/su-exec {{ db_user }} {{ db_executable_directory }}/pg_ctl stop -D {{ db_default_cluster_data_directory }}
  args:
    chdir: "{{ db_default_cluster_data_directory }}"
  when:
    - stat_default_db_data_directory.stat.exists
    - stat_default_db_pid.stat.exists
  tags:
    - database

- name: Remove existing default data directory
  file:
    path: "{{ db_default_cluster_data_directory }}"
    state: absent
  when:
    - stat_default_db_data_directory.stat.exists
  tags:
    - database

- name: Check if data directory already exists
  stat:
    path: "{{ db_data_directory }}/{{ db_node }}"
  register: stat_db_data_directory
  tags:
    - database

- name: Check if database is running
  stat:
    path: "{{ db_data_directory }}/{{ db_node }}/postmaster.pid"
  register: stat_db_pid
  tags:
    - database

- name: Stop running database server
  command: /usr/local/sbin/su-exec {{ db_user }} {{ db_executable_directory }}/pg_ctl stop -D {{ db_data_directory }}/{{ db_node }} -o "-p {{ db_port }}" -m smart
  args:
    chdir: "{{ db_data_directory }}"
  when:
    - stat_db_data_directory.stat.exists
    - stat_db_pid.stat.exists
  tags:
    - database

- name: Create log directory
  file:
    path: "{{ db_log_directory }}"
    state: directory
    recurse: yes
    owner: "{{ db_user }}"
    group: "{{ db_group }}"
    mode: 0700
  tags:
    - database

- name: Initialize database cluster
  command: /usr/local/sbin/su-exec {{ db_user }} {{ db_executable_directory }}/pg_ctl init -D {{ db_data_directory }}/{{ db_node }} -l {{ db_log_directory }}/postgresql-{{ db_node }}.log
  args:
    chdir: "{{ db_data_directory }}"
  when:
    - not stat_db_data_directory.stat.exists
  tags:
    - database

- name: Increase kernel limits for semaphores permanently
  template:
    src: pg_semaphores_limit.conf.j2
    dest: /etc/sysctl.d/99-pg_semaphores_limit.conf
  tags:
    - database

- name: Increase runtime kernel limits for semaphores
  shell: sysctl -w kernel.sem="250 60000 32 250"
  tags:
    - database

- name: Increaese limit for number of open files
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ db_user }} soft nofile {{ pg_max_files_per_process }}"
  tags:
    - database

- name: Place PostgreSQL systemd config file
  template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/postgresql@{{ db_node }}.service
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
  when:
    - ansible_env.ANSIBLE_CONTAINER is undefined
  tags:
    - database

- name: Create directory for PostgreSQL lock file
  file:
    path: /var/run/postgresql
    state: directory
    recurse: yes
    owner: "{{ db_user }}"
    group: "{{ db_group }}"
    mode: 0700
  tags:
    - database
