# TmDeploy - Automated setup and deployment of TissueMAPS in the cloud.
# Copyright (C) 2016-2019  University of Zurich

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---

- name: Create uWSGI log and metric directories
  file:
    path: '{{ item }}'
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0770
  with_items:
    - /var/log/uwsgi
    - /var/log/uwsgi/metrics
    - /var/run/uwsgi
  tags:
    - app-server
    - uwsgi

- name: Deploy uWSGI configuration and startup script
  template:
    src: 'uwsgi.ini.j2'
    dest: '/home/{{ tm_user }}/.tmaps/uwsgi.ini'
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 'ug+r,o-rwx'
  tags:
    - app-server
    - uwsgi

- name: Create directory for uWSGI pid file
  file:
    path: /var/run/uwsgi
    state: directory
    recurse: yes
    owner: "{{ tm_user }}"
    group: "{{ tm_group }}"
    mode: 0750
  tags:
    - app-server
    - uwsgi

- name: Place tmpfiles.d config file for uWSGI
  copy:
    content: |
      d /var/run/uwsgi 0750 {{ tm_user }} {{ tm_group }} -
      a+ /var/run/uwsgi - - - - u:{{ tm_group }}:rx
      a+ /var/run/uwsgi - - - - default:u:{{ tm_group }}:rw
    dest: /etc/tmpfiles.d/uwsgi.conf
    owner: root
    group: root
    mode: 0700
  when: ansible_env.ANSIBLE_CONTAINER is not defined
  tags:
    - app-server
    - uwsgi

- name: Deploy system-level uWSGI config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
  with_items:
    - src: uwsgi.logrotate.j2
      dest: '/etc/logrotate.d/tissuemaps.conf'
    # FIXME: we are using internal details of the `supervisord` role,
    # this may break if Ansible changes the visibility of role variables
    - src: tm_server.supervisord.j2
      dest: '{{ supervisor_conf_dir }}/tm_server.{{ supervisor_conf_suffix }}'
    - src: tm_jobdaemon.supervisord.j2
      dest: '{{ supervisor_conf_dir }}/tm_jobdaemon.{{ supervisor_conf_suffix }}'
  tags:
    - app-server
    - uwsgi
